development:
  adapter: mysql
  database: accounts_development
  username: root
  password:
  host: localhost
  pool: 5

test:
  adapter: mysql
  database: accounts_test
  username: root
  password:
  host: localhost
  pool: 5

production:
  adapter: mysql
  database: accounts_production
  username: mrudhu
  password: jaisreeram
  host: localhost